services:
  grafana:
    extends:
      file: ./grafana/docker-compose.yml
      service: grafana

  prometheus:
    extends:
      file: ./prometheus/docker-compose.yml
      service: prometheus

  loki:
    extends:
      file: ./loki/docker-compose.yml
      service: loki
