services:
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./config:/etc/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
